export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
//export const AUTH_ERROR = 'AUTH_ERROR';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const PASSWORD_RESET_FAIL = 'PASSWORD_RESET_FAIL';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL = 'GET_USER_FAIL';

// GOALS
export const CREATE_GOAL_SUCCESS = 'CREATE_GOAL_SUCCESS';
export const CREATE_GOAL_FAIL = 'CREATE_GOAL_FAIL';

export const GET_ALL_SUCCESS = 'GET_ALL_SUCCESS';
export const GET_ALL_FAIL = 'GET_ALL_FAIL';

export const GET_ONE_SUCCESS = 'GET_ONE_SUCCESS';
export const GET_ONE_FAIL = 'GET_ONE_FAIL';

export const UPDATE_GOAL_SUCCESS = 'UPDATE_GOAL_SUCCESS';
export const UPDATE_GOAL_FAIL = 'UPDATE_GOAL_FAIL';

export const DELETE_GOAL_SUCCESS = 'DELETE_GOAL_SUCCESS';
export const DELETE_GOAL_FAIL = 'DELETE_GOAL_FAIL';

export const DELETE_ALL_GOALS_SUCCESS = 'DELETE_ALL_GOALS_SUCCESS';
export const DELETE_ALL_GOALS_FAIL = 'DELETE_ALL_GOALS_FAIL';

export const FLIP_SUBMIT = 'FLIP_SUBMIT';